# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd4813a7ae95e6f3a4131cc82488cfd438d48b6dc01f8522cb48f919ca00755b411c1e8e22738a3b6c8e362e16833cbc763de418f501aa637e9baf5d330c349e

test:
  secret_key_base: e77ca9e025371ff1b4eb478d4b31d131a6cb8ef5168c58d47baa2863d47779c2b952c9f8862bba0a662ddbff6e8e2af588b30aa67ba8745a273952affac418e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
